# The URL the site will be built for
base_url = "https://neon-leitz.github.io/twi-booru-stats"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
# Put all your custom variables here
navbar_items = [
    { code = "en", nav_items = [
        { url = "$BASE_URL/", name = "Home" },
        { url = "$BASE_URL/charts/uploads", name = "Uploads" },
        { url = "$BASE_URL/charts/characters", name = "Characters" },
        { url = "$BASE_URL/charts/artists", name = "Artists" },
        { url = "$BASE_URL/charts/books", name = "Books" },
        { url = "$BASE_URL/charts/volumes", name = "Volumes" },
        { url = "$BASE_URL/charts/filetypes", name = "Filetypes" },
    ] },
]

